export const UPDATE_PAGE_URLS = 'UPDATE_PAGE_URLS';
export const UPDATE_PAGE_INFO = 'UPDATE_PAGE_INFO';
export const UPDATE_PAGE_POST = 'UPDATE_PAGE_POST';
export const SUMMARIZE_PAGE_INFO = 'SUMMARIZE_PAGE_INFO';
export const UPDATE_TIME = 'UPDATE_TIME';