export const UPDATE_PAGE_PICTURE = 'UPDATE_PAGE_PICTURE';
export const UPDATE_PAGE_POST = 'UPDATE_PAGE_POST';
export const UPDATE_PAGE_NAME = 'UPDATE_PAGE_NAME';
export const UPDATE_FAN_COUNT = 'UPDATE_FAN_COUNT';
